---
title: "03_atmospheric_correction"
author: "Arthur de Grandpré, UQTR, arthur.de.grandpre@uqtr.ca"
date: "2 mars 2020"
output: 
  html_document: 
    keep_md: yes
    toc: yes
    toc_float: yes
---

This third script is used to go from top of atmosphere reflectance values to bottom of atmosphere reflectance based on an image based, empirical atmospheric correction model. The necessary inputs depend on the previous scripts, 01_metadata_extraction and 02_radiometric_correction.

The methods used are detailed in :

A first step before calibration will be to mosaic together all comparable images (some difference remain between them even after calibration), in order for smaller areas to be better corrected based on other images data.

# R setup

All libraries must be installed prior to loading them. Installing them individually is the best course of action, using the install.packages("nameofthepackage") function.

**important : ** Do not forget to change the tmpdir path in the setup code chunk to a disk with a lot of free space. The raster options prevent the data from being all loaded into the RAM and crashing the process due to lack of memory, thus requiring to write large amounts of intermediate products.

```{r setup, message=F, warning=F}
rm(list=ls())
library(sf)
library(raster)
library(tidyverse)
library(data.table)
library(satellite)
library(GeoLight)
library(sp)
library(stringr)
# library(doParallel) # could be added at some point to speedup the process
# library(foreach) # could be added at some point to speedup the process

# raster options
rasterOptions(todisk=T) # forces on disk writing instead of in memory
rasterOptions(tmpdir="D:/Arthur/temp") # requires a lot of space for temporary file
```
